# Generated by Django 5.2.7 on 2025-11-02 10:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='顾客ID')),
                ('name', models.CharField(max_length=40, verbose_name='名字')),
                ('nick_name', models.CharField(blank=True, max_length=40, verbose_name='昵称')),
                ('real_name', models.CharField(blank=True, max_length=40, verbose_name='真实姓名')),
                ('mobile_phone', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('fixed_phone', models.CharField(blank=True, max_length=11, verbose_name='固话')),
                ('from_platform', models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, '美团'), (2, '大众点评'), (3, '抖音'), (4, '微信'), (5, 'QQ'), (6, '线下'), (7, 'B站'), (8, '快手'), (9, '西瓜'), (10, '微视')], default=0, verbose_name='来自平台')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, '男性'), (2, '女性')], default=0, verbose_name='性别')),
                ('language', models.CharField(blank=True, max_length=50, verbose_name='语言')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='省份')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='国家')),
                ('avatar_url', models.CharField(blank=True, max_length=500, verbose_name='头像')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP客户')),
                ('recharge_amount', models.FloatField(default=0, verbose_name='剩余金额')),
                ('description', models.TextField(default='无', max_length=400, verbose_name='介绍')),
                ('mark', models.TextField(default='这个人很懒，什么都没有留下', max_length=400, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '顾客表',
                'verbose_name_plural': '顾客表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MasterInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='名字')),
                ('nick_name', models.CharField(blank=True, max_length=40, verbose_name='昵称')),
                ('number_ticket', models.IntegerField(default=1, verbose_name='号位')),
                ('gender', models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, '男性'), (2, '女性')], default=0, verbose_name='性别')),
                ('date_of_entry', models.DateField(default=datetime.date.today, verbose_name='入职日期')),
                ('date_of_departure', models.DateField(default=datetime.date.today, verbose_name='离职日期')),
                ('at_post', models.BooleanField(default=False, verbose_name='是否在职')),
                ('mark', models.TextField(default='这个人很懒，什么都没有留下', max_length=400, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '师傅表',
                'verbose_name_plural': '师傅表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OptionRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=2000, verbose_name='记录内容')),
                ('mark', models.TextField(default='这个人很懒，什么都没有留下', max_length=400, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '操作记录表',
                'verbose_name_plural': '操作记录表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, verbose_name='项目名字')),
                ('full_name', models.CharField(max_length=80, verbose_name='项目全称')),
                ('use_type', models.PositiveSmallIntegerField(choices=[(1, '金额'), (2, '次卡')], default=1, verbose_name='使用类型')),
                ('frequency_count', models.IntegerField(default=0, verbose_name='次卡：次数')),
                ('full_price', models.FloatField(default=0, verbose_name='定价：元')),
                ('discount_number', models.FloatField(default=1.0, verbose_name='折扣力度：0-1.0')),
                ('final_price', models.FloatField(default=0, verbose_name='最终价格')),
                ('on_the_shelf', models.BooleanField(default=True, verbose_name='是否上架')),
                ('description', models.TextField(default='无', max_length=400, verbose_name='介绍')),
                ('mark', models.TextField(default='这个人很懒，什么都没有留下', max_length=400, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('valid_time', models.IntegerField(default=30, verbose_name='有效时长，单位:天')),
                ('mark', models.TextField(default='这个人很懒，什么都没有留下', max_length=400, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('from_platform', models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, '美团'), (2, '大众点评'), (3, '抖音'), (4, '微信'), (5, 'QQ'), (6, '线下'), (7, 'B站'), (8, '快手'), (9, '西瓜'), (10, '微视')], default=0, verbose_name='来源')),
                ('received_money', models.FloatField(default=0, verbose_name='实收金额')),
                ('received_count', models.IntegerField(default=0, verbose_name='总次数')),
                ('used_end', models.BooleanField(default=False, verbose_name='是否已经使用完毕')),
                ('mark', models.TextField(default='这个人很懒，什么都没有留下', max_length=400, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.customerinfo')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.product')),
            ],
            options={
                'verbose_name': '订单表',
                'verbose_name_plural': '订单表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time_1_start', models.DateTimeField(auto_now_add=True, verbose_name='第1个项目开始时间')),
                ('order_time_1_end', models.DateTimeField(auto_now_add=True, verbose_name='第1个项目结束时间')),
                ('order_time_2_start', models.DateTimeField(auto_now_add=True, verbose_name='第2个项目开始时间')),
                ('order_time_2_end', models.DateTimeField(auto_now_add=True, verbose_name='第2个项目结束时间')),
                ('order_time_3_start', models.DateTimeField(auto_now_add=True, verbose_name='第3个项目开始时间')),
                ('order_time_3_end', models.DateTimeField(auto_now_add=True, verbose_name='第3个项目结束时间')),
                ('order_time_4_start', models.DateTimeField(auto_now_add=True, verbose_name='第4个项目开始时间')),
                ('order_time_4_end', models.DateTimeField(auto_now_add=True, verbose_name='第4个项目结束时间')),
                ('order_time_5_start', models.DateTimeField(auto_now_add=True, verbose_name='第5个项目开始时间')),
                ('order_time_5_end', models.DateTimeField(auto_now_add=True, verbose_name='第5个项目结束时间')),
                ('consumption_1_type', models.PositiveSmallIntegerField(choices=[(1, '金额'), (2, '次卡')], default=1, verbose_name='第1个项目消费类型')),
                ('consumption_2_type', models.PositiveSmallIntegerField(choices=[(1, '金额'), (2, '次卡')], default=1, verbose_name='第2个项目消费类型')),
                ('consumption_3_type', models.PositiveSmallIntegerField(choices=[(1, '金额'), (2, '次卡')], default=1, verbose_name='第3个项目消费类型')),
                ('consumption_4_type', models.PositiveSmallIntegerField(choices=[(1, '金额'), (2, '次卡')], default=1, verbose_name='第4个项目消费类型')),
                ('consumption_5_type', models.PositiveSmallIntegerField(choices=[(1, '金额'), (2, '次卡')], default=1, verbose_name='第5个项目消费类型')),
                ('mark', models.TextField(default='这个人很懒，什么都没有留下', max_length=400, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('real_customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.customerinfo')),
                ('order_1_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field1', to='feedback.masterinfo')),
                ('order_2_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field2', to='feedback.masterinfo')),
                ('order_3_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field3', to='feedback.masterinfo')),
                ('order_4_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field4', to='feedback.masterinfo')),
                ('order_5_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field5', to='feedback.masterinfo')),
                ('order1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_order_field1', to='feedback.orderinfo')),
                ('order2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_order_field2', to='feedback.orderinfo')),
                ('order3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_order_field3', to='feedback.orderinfo')),
                ('order4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_order_field4', to='feedback.orderinfo')),
                ('order5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_order_field5', to='feedback.orderinfo')),
            ],
            options={
                'verbose_name': '消费记录表',
                'verbose_name_plural': '消费记录表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RechargeRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='金额')),
                ('mark', models.TextField(default='这个人很懒，什么都没有留下', max_length=400, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.customerinfo')),
            ],
            options={
                'verbose_name': '充值记录表',
                'verbose_name_plural': '充值记录表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(blank=True, max_length=40, verbose_name='师傅名字')),
                ('service_progress', models.PositiveSmallIntegerField(choices=[(1, '不好'), (2, '一般'), (3, '很好'), (4, '非常好')], default=4, verbose_name='服务流程')),
                ('master_technique', models.PositiveSmallIntegerField(choices=[(1, '不好'), (2, '一般'), (3, '很好'), (4, '非常好')], default=4, verbose_name='技师手法')),
                ('environment', models.PositiveSmallIntegerField(choices=[(1, '不好'), (2, '一般'), (3, '很好'), (4, '非常好')], default=4, verbose_name='环境卫生')),
                ('content', models.TextField(max_length=500, verbose_name='反馈内容')),
                ('mark', models.TextField(default='这个人很懒，什么都没有留下', max_length=400, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.customerinfo')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.product')),
                ('verification_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.verificationcode')),
            ],
            options={
                'verbose_name': '反馈表',
                'verbose_name_plural': '反馈表',
                'ordering': ['-id'],
            },
        ),
    ]
