# Generated by Django 5.2.7 on 2025-10-18 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Null', max_length=40, verbose_name='项目名字')),
                ('description', models.TextField(default='无', max_length=400, verbose_name='介绍')),
                ('mark', models.TextField(default='这个人很懒，什么都没有留下', max_length=400, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShopUserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='顾客ID')),
                ('name', models.CharField(default='Null', max_length=40, verbose_name='名字')),
                ('nick_name', models.CharField(default='Null', max_length=40, verbose_name='昵称')),
                ('mobile_phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('fixed_phone', models.CharField(max_length=11, verbose_name='固话')),
                ('from_platform', models.CharField(choices=[(1, '微信'), (2, 'QQ'), (3, '线下'), (4, '大众点评'), (5, '抖音'), (6, 'B站'), (7, '快手'), (8, '西瓜'), (9, '微视')], default=1, max_length=100, verbose_name='来自平台')),
                ('description', models.TextField(default='无', max_length=400, verbose_name='介绍')),
                ('mark', models.TextField(default='这个人很懒，什么都没有留下', max_length=400, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '顾客表',
                'verbose_name_plural': '顾客表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('valid_time', models.IntegerField(default=30, verbose_name='有效时长，单位:天')),
                ('mark', models.TextField(default='这个人很懒，什么都没有留下', max_length=400, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(max_length=40, verbose_name='师傅名字')),
                ('service_progress', models.CharField(choices=[(1, '微信'), (2, 'QQ'), (3, '线下'), (4, '大众点评'), (5, '抖音'), (6, 'B站'), (7, '快手'), (8, '西瓜'), (9, '微视')], default=1, max_length=100, verbose_name='服务流程')),
                ('master_technique', models.CharField(choices=[(1, '不好'), (2, '一般'), (3, '很好'), (4, '非常好')], default=4, max_length=100, verbose_name='技师手法')),
                ('environment', models.CharField(choices=[(1, '不好'), (2, '一般'), (3, '很好'), (4, '非常好')], default=4, max_length=100, verbose_name='环境卫生')),
                ('content', models.TextField(max_length=500, verbose_name='反馈内容')),
                ('mark', models.TextField(default='这个人很懒，什么都没有留下', max_length=400, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.product')),
                ('verification_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.verificationcode')),
            ],
            options={
                'verbose_name': '反馈表',
                'verbose_name_plural': '反馈表',
                'ordering': ['-id'],
            },
        ),
    ]
