# Generated by Django 5.2.7 on 2025-11-06 17:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_order_field1', to='feedback.orderinfo', verbose_name='订单1'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_order_field2', to='feedback.orderinfo', verbose_name='订单2'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_order_field3', to='feedback.orderinfo', verbose_name='订单3'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_order_field4', to='feedback.orderinfo', verbose_name='订单4'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_order_field5', to='feedback.orderinfo', verbose_name='订单5'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_1_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field1', to='feedback.masterinfo', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_2_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field2', to='feedback.masterinfo', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_3_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field3', to='feedback.masterinfo', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_4_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field4', to='feedback.masterinfo', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_5_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field5', to='feedback.masterinfo', verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 6, 28, 437888), verbose_name='第1个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 6, 28, 437863), verbose_name='第1个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 6, 28, 437901), verbose_name='第2个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 6, 28, 437895), verbose_name='第2个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 6, 28, 437912), verbose_name='第3个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 6, 28, 437906), verbose_name='第3个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 6, 28, 437923), verbose_name='第4个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 6, 28, 437917), verbose_name='第4个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 6, 28, 437933), verbose_name='第5个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 6, 28, 437928), verbose_name='第5个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='real_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.customerinfo', verbose_name='顾客'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.product', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.customerinfo', verbose_name='顾客'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='verification_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.verificationcode', verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.customerinfo', verbose_name='顾客'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.product', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='rechargerecord',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.customerinfo', verbose_name='顾客'),
        ),
    ]
