# Generated by Django 5.2.7 on 2025-10-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserinfo',
            name='avatar_url',
            field=models.CharField(default='', max_length=500, verbose_name='头像'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopuserinfo',
            name='city',
            field=models.CharField(default='', max_length=50, verbose_name='城市'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopuserinfo',
            name='country',
            field=models.CharField(default='', max_length=50, verbose_name='国家'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopuserinfo',
            name='gender',
            field=models.CharField(choices=[(0, '未知'), (1, '男性'), (2, '女性')], default=0, max_length=100, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='shopuserinfo',
            name='language',
            field=models.CharField(default='', max_length=50, verbose_name='语言'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopuserinfo',
            name='province',
            field=models.CharField(default='', max_length=50, verbose_name='省份'),
            preserve_default=False,
        ),
    ]
