# Generated by Django 5.2.7 on 2025-10-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_shopuserinfo_avatar_url_shopuserinfo_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='service_progress',
            field=models.CharField(choices=[(1, '不好'), (2, '一般'), (3, '很好'), (4, '非常好')], default=4, max_length=100, verbose_name='服务流程'),
        ),
    ]
