# Generated by Django 5.2.7 on 2025-11-06 17:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_consumptionrecord_order1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_1_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field1', to='feedback.masterinfo', verbose_name='订单1对应师傅'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_2_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field2', to='feedback.masterinfo', verbose_name='订单2对应师傅'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_3_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field3', to='feedback.masterinfo', verbose_name='订单3对应师傅'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_4_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field4', to='feedback.masterinfo', verbose_name='订单4对应师傅'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_5_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field5', to='feedback.masterinfo', verbose_name='订单5对应师傅'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 9, 31, 219831), verbose_name='第1个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 9, 31, 219804), verbose_name='第1个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 9, 31, 219844), verbose_name='第2个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 9, 31, 219838), verbose_name='第2个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 9, 31, 219855), verbose_name='第3个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 9, 31, 219850), verbose_name='第3个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 9, 31, 219867), verbose_name='第4个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 9, 31, 219861), verbose_name='第4个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 9, 31, 219878), verbose_name='第5个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 9, 31, 219873), verbose_name='第5个项目开始时间'),
        ),
    ]
