# Generated by Django 5.2.7 on 2025-10-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_service_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='verification_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.verificationcode'),
        ),
    ]
