# Generated by Django 5.2.7 on 2025-11-06 17:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_consumptionrecord_order_1_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_order_field1', to='feedback.orderinfo', verbose_name='订单1'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_order_field2', to='feedback.orderinfo', verbose_name='订单2'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_order_field3', to='feedback.orderinfo', verbose_name='订单3'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_order_field4', to='feedback.orderinfo', verbose_name='订单4'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_order_field5', to='feedback.orderinfo', verbose_name='订单5'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 10, 27, 548854), verbose_name='第1个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 10, 27, 548829), verbose_name='第1个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 10, 27, 548866), verbose_name='第2个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 10, 27, 548861), verbose_name='第2个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 10, 27, 548877), verbose_name='第3个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 10, 27, 548872), verbose_name='第3个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 10, 27, 548889), verbose_name='第4个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 10, 27, 548883), verbose_name='第4个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 10, 27, 548900), verbose_name='第5个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 10, 27, 548894), verbose_name='第5个项目开始时间'),
        ),
    ]
