# Generated by Django 5.2.7 on 2025-11-06 17:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_alter_consumptionrecord_order1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionrecord',
            name='consumption_1_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '金额'), (2, '次卡')], default=1, verbose_name='订单1消费类型'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='consumption_2_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '金额'), (2, '次卡')], default=1, verbose_name='订单2消费类型'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='consumption_3_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '金额'), (2, '次卡')], default=1, verbose_name='订单3消费类型'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='consumption_4_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '金额'), (2, '次卡')], default=1, verbose_name='订单4消费类型'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='consumption_5_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '金额'), (2, '次卡')], default=1, verbose_name='订单5消费类型'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_1_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field1', to='feedback.masterinfo', verbose_name='订单1对应师傅'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_2_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field2', to='feedback.masterinfo', verbose_name='订单2对应师傅'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_3_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field3', to='feedback.masterinfo', verbose_name='订单3对应师傅'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_4_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field4', to='feedback.masterinfo', verbose_name='订单4对应师傅'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_5_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumption_2_master_field5', to='feedback.masterinfo', verbose_name='订单5对应师傅'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 15, 38, 62156), verbose_name='第1个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 15, 38, 62132), verbose_name='第1个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 15, 38, 62169), verbose_name='第2个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 15, 38, 62163), verbose_name='第2个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 15, 38, 62181), verbose_name='第3个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 15, 38, 62175), verbose_name='第3个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 15, 38, 62192), verbose_name='第4个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 15, 38, 62187), verbose_name='第4个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 15, 38, 62203), verbose_name='第5个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 7, 1, 15, 38, 62198), verbose_name='第5个项目开始时间'),
        ),
    ]
