# Generated by Django 5.2.7 on 2025-11-16 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_alter_consumptionrecord_consumption_1_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '推拿/按摩'), (2, '精油SPA'), (3, '采耳'), (4, '艾灸'), (5, '拔罐'), (6, '刮痧'), (7, '次卡')], default=1, verbose_name='项目类型'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 21, 14, 10, 1577), verbose_name='第1个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 21, 14, 10, 1527), verbose_name='第1个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 21, 14, 10, 1597), verbose_name='第2个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 21, 14, 10, 1588), verbose_name='第2个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 21, 14, 10, 1614), verbose_name='第3个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 21, 14, 10, 1605), verbose_name='第3个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 21, 14, 10, 1634), verbose_name='第4个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 21, 14, 10, 1624), verbose_name='第4个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 21, 14, 10, 1734), verbose_name='第5个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 21, 14, 10, 1644), verbose_name='第5个项目开始时间'),
        ),
    ]
