# Generated by Django 5.2.7 on 2025-11-16 14:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_product_sub_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotProductInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000, verbose_name='标题')),
                ('img_url', models.CharField(max_length=2000, verbose_name='图片地址')),
                ('jump_url', models.CharField(max_length=2000, verbose_name='跳转地址')),
                ('mark', models.TextField(default='这个人很懒，什么都没有留下', max_length=400, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '热门项目表',
                'verbose_name_plural': '充值记录表',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='bg_img',
            field=models.ImageField(blank=True, upload_to='products/images/', verbose_name='项目展示图'),
        ),
        migrations.AddField(
            model_name='product',
            name='vip_price',
            field=models.FloatField(default=0, verbose_name='VIP价格'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 4, 55, 329407), verbose_name='第1个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 4, 55, 329381), verbose_name='第1个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 4, 55, 329419), verbose_name='第2个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 4, 55, 329413), verbose_name='第2个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 4, 55, 329430), verbose_name='第3个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 4, 55, 329424), verbose_name='第3个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 4, 55, 329441), verbose_name='第4个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 4, 55, 329435), verbose_name='第4个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 4, 55, 329453), verbose_name='第5个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 4, 55, 329447), verbose_name='第5个项目开始时间'),
        ),
        migrations.CreateModel(
            name='ListedInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_platform', models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, '美团'), (2, '大众点评'), (3, '抖音'), (4, '微信'), (5, 'QQ'), (6, '线下'), (7, 'B站'), (8, '快手'), (9, '西瓜'), (10, '微视')], default=1, verbose_name='项目类型')),
                ('exp_price', models.FloatField(default=0, verbose_name='体验价')),
                ('bug_jump_url', models.CharField(blank=True, max_length=500, verbose_name='购买跳转链接')),
                ('mark', models.TextField(default='这个人很懒，什么都没有留下', max_length=400, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedback.product', verbose_name='项目')),
            ],
            options={
                'verbose_name': '平台上架表',
                'verbose_name_plural': '平台上架表',
                'ordering': ['id'],
            },
        ),
    ]
