# Generated by Django 5.2.7 on 2025-11-16 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_hotproductinfo_product_bg_img_product_vip_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 6, 34, 949342), verbose_name='第1个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 6, 34, 949315), verbose_name='第1个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 6, 34, 949354), verbose_name='第2个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 6, 34, 949348), verbose_name='第2个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 6, 34, 949366), verbose_name='第3个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 6, 34, 949360), verbose_name='第3个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 6, 34, 949379), verbose_name='第4个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 6, 34, 949373), verbose_name='第4个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 6, 34, 949390), verbose_name='第5个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 16, 22, 6, 34, 949384), verbose_name='第5个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='listedinfo',
            name='listed_platform',
            field=models.PositiveSmallIntegerField(choices=[(0, '未知'), (1, '美团'), (2, '大众点评'), (3, '抖音'), (4, '微信'), (5, 'QQ'), (6, '线下'), (7, 'B站'), (8, '快手'), (9, '西瓜'), (10, '微视')], default=1, verbose_name='上架平台'),
        ),
    ]
