# Generated by Django 5.2.7 on 2025-12-04 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_alter_consumptionrecord_order_time_1_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exp_price',
            field=models.FloatField(default=0, verbose_name='体验价'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 4, 21, 4, 55, 278746), verbose_name='第1个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_1_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 4, 21, 4, 55, 278724), verbose_name='第1个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 4, 21, 4, 55, 278758), verbose_name='第2个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_2_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 4, 21, 4, 55, 278752), verbose_name='第2个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 4, 21, 4, 55, 278768), verbose_name='第3个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_3_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 4, 21, 4, 55, 278763), verbose_name='第3个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 4, 21, 4, 55, 278780), verbose_name='第4个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_4_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 4, 21, 4, 55, 278775), verbose_name='第4个项目开始时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 4, 21, 4, 55, 278790), verbose_name='第5个项目结束时间'),
        ),
        migrations.AlterField(
            model_name='consumptionrecord',
            name='order_time_5_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 4, 21, 4, 55, 278785), verbose_name='第5个项目开始时间'),
        ),
    ]
