NO_ERROR = 0
VERIFICATION_NO_CODE = 1    # 没有验证码
VERIFICATION_CODE_ERROR = 2    # 没有验证码
PHONE_NUMBER_FORMAT_CODE = 3    # 手机号格式错误

ERROR_ENUM = {
    VERIFICATION_NO_CODE: '没有验证码',
    VERIFICATION_CODE_ERROR: '没有验证码',
    PHONE_NUMBER_FORMAT_CODE: '手机号格式错误'
}
